### ISSUE TITLE
Development progress.

### ISSUE THREAD

**Issue by Ionizing** [Ionizing/wavecar_rs#1]
# Current progress (Jul 9 2020) :

- [x] Standard WAVECAR parsing;
- [x] Gamma only WAVECAR parsing;
- [x] Spin orbit coupling WAVECAR parsing;
- [x] Get wave function coefficients;
- [x] Apply reverse FFT to get the wave function in real space;
- [x] Apply phase on wave function in real space;

**Comment by Ionizing** [comment]
# TODOs (Jul 9 2020) :

- [x] API invoking should be like:
```rust
Wavecar::from_file("path/to/wavecar/")
  .get_wavefunction_in_realspace(ispin, ikpoint, iband, ngrid)
  .apply_phase(r0)
  .normalize()
  .save_as_chgcar()
```
or
```rust
Wavecar::from_file("path/to/wavecar/")
  .get_wavefunction_in_realspace(ispin, ikpoint, iband, ngrid)
  .apply_phase(r0)
  .normalize()
  .into_charge_density()
```
A helper trait may be useful;

- [x] Add a function that allow user to set the vasp type in order to resolve the failure in determining the gamma only WAVECAR;
- [x] And a function like `get_wavefunction_in_realspace` without requiring `ngrid` should be implemented, in order to simplify the invoking; Done via `get_wavefunction_in_realspace_dn`, where `dn` means 'default ngrid'.
- [ ] ~~Calculate the E-fermi from WAVECAR if we cannot find it from WAVECAR directly;~~ **Cannot be calculated without k-points' weights information**
- [ ] ~~Maybe we should use `[u64; 3]` to store `ngrid`;  **REJECTED**~~
- [x] Struct of `WaveFunction` should be designed carefully;
- [x] Save wave function as CHGCAR function, sign of coefficient should be reserved;
- [x] Save charge density as PARCHG function, |\psi|^2 should be used; Need to be done with [vaspchg_rs](https://github.com/Ionizing/vaspchg_rs)
- [ ] A function that selecting multiple [spins/spinors, kpoints, bands] and calculate the total charge density;

**Comment by Ionizing** [comment]
# GUI related

- [X] Framework: [gtk-rs](https://gtk-rs.org), gtk's: [tutorial](https://github.com/RainMark/gtk3-tutorial)

Won't implement. Maybe create another crate is needed to do this.

**Comment by Ionizing** [comment]
- [ ] Add a binary to list the WAVECAR information. Will be implemented in the NEAR future
